language: python
services:
    - mongodb
    - redis-server
    - rabbitmq
python: 2.7
install:
    - pip install -r requirements.txt
    - cp config.py.dist config.py
    - echo ACTIVATE_TRANSLATOR = True >> config.py
    - echo ACTIVATE_TRANSLATOR_MONGODB_PUSHES = True >> config.py
#    - alembic upgrade head
#before_script:
#    - nohup python run.py &
#    - export SELENIUM_HEADLESS=ENABLE
script:
#    - echo "Tests not executed"
    - nosetests appcomposer
#    - nosetests appcomposer/selenium/*.py
